name: test

on: [pull_request, push]

jobs:
  pytest:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # don't cancel other matrix jobs when one fails
      matrix:
        python-version: ["3.10"]
        # Test two environments:
        # 1) dependencies with pinned versions from requirements.txt
        # 2) 'pip install --upgrade --upgrade-strategy=eager .' to install upgraded
        #    dependencies from PyPI using version ranges defined within pyproject.toml
        env: [
          '-r requirements.txt .[all]'
        ]
        include:
          - python-version: "3.8"
          - python-version: "3.13"
            env: '--upgrade --upgrade-strategy=eager .[all]'
          - python-version: "3.14"
            env: '--upgrade --upgrade-strategy=eager .[all]'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install ${{ matrix.env }}
      run: |
        pip install ${{ matrix.env }}
        pip install coveralls wheel

    - name: Test with pytest ${{ matrix.env }}
      run: |
        pytest --cov=bifacialvf

#    - name: Coveralls
#      run: |
#        coveralls --service=github
#      env: 
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

